# Generated by Django 3.2.3 on 2021-06-16 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0007_auto_20210518_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('myFiles', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(default=datetime.datetime(2021, 6, 16, 23, 43, 35, 598822), max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_interaction',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 23, 43, 35, 598822)),
        ),
    ]
