# Generated by Django 3.2.3 on 2021-06-16 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0008_auto_20210616_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(default=datetime.datetime(2021, 6, 16, 23, 50, 27, 845262), max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_interaction',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 23, 50, 27, 845262)),
        ),
    ]
